name: Daily Valuation

on:
  push:
    branches:
      - 'main'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Daily Valuation
      run: |
        python valuation/value_daily.py
        git add .
        git commit -m "completing today's valuation"
